# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vVZDYO8ljat6FT0LTG3-TneBagYe71Hu
"""

from pylab import *
from skimage import img_as_float

i = imread('/content/data/1.jpeg')
imshow(i);

j = imread('/content/data/2.jpeg')
imshow(j)

k = imread('/content/data/3.jpeg')
imshow(k);

l = imread('/content/data/4.jpeg')
imshow(l);

m = imread('/content/data/5.jpeg')
imshow(m);

n = imread('/content/data/6.jpeg')
imshow(n);

o = imread('/content/data/7.jpeg')
imshow(o);

import cv2
import numpy as np
from imhist import imhist, imcdf
import matplotlib.pyplot as plt

imhist(Red);

imhist(Green);

resized = cv2.resize(i, (600,400))
plt.imshow(resized)

resized = cv2.resize(j, (600,400))
plt.imshow(resized)

resized = cv2.resize(k, (600,400))
plt.imshow(resized)

resized = cv2.resize(l, (600,400))
plt.imshow(resized)

resized = cv2.resize(m, (600,400))
plt.imshow(resized)

resized = cv2.resize(n, (600,400))
plt.imshow(resized)

resized = cv2.resize(o, (600,400))
plt.imshow(resized)

